### ISSUE TITLE
Not indented correctly

### ISSUE THREAD

**Issue by parth-gr** [rook/kubectl-rook-ceph#41] opened 2022-08-01 11:58 UTC
https://github.com/rook/kubectl-rook-ceph/blob/ef787842a5e73ecac7687cb7706254e574b44d9e/.github/workflows/ci-for-diff-ns.yaml#L56

This should be `kubectl rook_ceph ...`

**Comment by parth-gr** [comment] 2022-08-01 12:01
ALso need to investigate in the CI why it was passing even with this bug.

**Comment by parth-gr** [comment] 2022-08-01 13:06
Also somewhere there should be mentioned that `flags` should be only used before the arguments and commands.
For example:           kubectl rook_ceph -o test-operator -n test-cluster ceph status

**Comment by subhamkrai** [comment] 2022-08-01 13:13
> ALso need to investigate in the CI why it was passing even with this bug.

this is not a bug, kubectl-rook_ceph or kubectl rook_ceph behaves the same since we install kubectl-rook_ceph in the $PATH
and kubectl treat it as plugin

**Comment by parth-gr** [comment] 2022-08-01 15:44
> > ALso need to investigate in the CI why it was passing even with this bug.
> 
> this is not a bug, kubectl-rook_ceph or kubectl rook_ceph behaves the same since we install kubectl-rook_ceph in the $PATH and kubectl treat it as plugin

Any specific reason to install this too kubectl-rook_ceph

**Comment by subhamkrai** [comment] 2022-08-08 04:29
> > > ALso need to investigate in the CI why it was passing even with this bug.
> > 
> > 
> > this is not a bug, kubectl-rook_ceph or kubectl rook_ceph behaves the same since we install kubectl-rook_ceph in the $PATH and kubectl treat it as plugin
> 
> Any specific reason to install this too kubectl-rook_ceph

yes, to accept the tool as kubectl plugin it should have prefix of `kubectl-`

**Comment by subhamkrai** [comment] 2022-10-19 09:36
@parth-gr can we close this?

**Closed** 2022-10-26 02:47 UTC
